# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  app:
    build:
      context: .
      target: final
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - 8080:8080
    depends_on:
     redis:
       condition: service_healthy

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5

  redis_exporter:
    image: oliver006/redis_exporter:v1.59.0
    ports:
      - "9121:9121"
    depends_on:
      - redis

  blackbox_exporter:
    image: prom/blackbox-exporter
    volumes:
      - ./prometheus/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - "9115:9115"

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.2
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  redis-data:
  prometheus_data:
  grafana-data:

